### PR TITLE
Add XML schema validation

### PR DESCRIPTION
**Pull request by sobolewskikamil**
Solved #45

### CODE REVIEW

**Comment by sobolewskikamil** [comment]
@krzysztofreczek Thanks for the review. Unfortunately currently I am not able to assign myself to any issue. This might be a matter of repository settings.

**Comment by SabreInc** [comment]
Hi Guys, everyone is welcome to contribute! Changed settings - you should be able to assign yourself now. Thanks

**Comment by lzmudzinski** [comment]
Hi Guys, everyone is welcome to contribute! Changed settings - you should now be able to assign yourself. Thanks

**Comment by sobolewskikamil** [comment]
@lzmudzinski, I am still not able to assign myself to any issue. I am not sure whether I'm doing something wrong.

**Comment by sobolewskikamil** [comment]
According to this GitHub issue https://github.com/isaacs/github/issues/100, it is impossible for contributors to assign themselves to issues.

**Comment by lzmudzinski** [comment]
Let's try a different way. You should get an invite to collaborate. Please accept and try again.

**Comment by sobolewskikamil** [comment]
@lzmudzinski Now it works. Thanks.

**Pull request merged**
